Properly handle ksvc bandwidth allocation
versatica/mediasoup pull request #1036
Opened 2023-03-28 17:03 UTC by vpalmisano

When we use VP9 with K-SVC configuration, the spatial layers are independent; this means that the bandwidth allocator, when it tries to increase the allocated layer,  should not take into account the lower spatial levels bitrates (same behaviour of the Simulcast case).

2023-03-28 17:37 UTC, ibc reviewed
Are you sure we don't need similar logic in ApplyBitrate() method?

2023-03-28 17:47 UTC, vpalmisano commented
> Are you sure we don't need similar logic in ApplyBitrate() method?

Do you mean taking into account that logic when we pass `maxBitrate` to the congestion controller?

2023-03-28 19:17 UTC, ibc commented
Nope, I mean another thing but maybe we changed it long ago and what I said no longer makes sense. Will recheck tomorrow.

2023-03-29 10:26 UTC, ibc commented
Checking this.

2023-03-29 12:51 UTC, ibc commented
Checking it later today.

2023-03-29 15:02 UTC, ibc requested changes
Ok @vpalmisano, I found the missing thing:

- See `SimulcastConsumer::GetDesiredBitrate()`. It returns the highest bitrate of all its streams (or `this->rtpParameters.encodings[0].maxBitrate` if given).
- However `SvcConsumer::GetDesiredBitrate()` returns the total bitrate of the whole SVC or K-SVC stream. If K-SVC we should just return the bitrate of the spatial layer that produces the most bitrate, right?

NOTE: `Consumer::GetDesiredBitrate()` is used by `Transport::ComputeOutgoingDesiredBitrate()` method.

2023-03-29 16:23 UTC, vpalmisano commented
> * If K-SVC we should just return the bitrate of the spatial layer that produces more bitrate, right?

Correct, I'm taking a look.

2023-03-29 17:17 UTC, ibc reviewed
Will review tomorrow. Thanks.

2023-03-30 09:50 UTC, ibc commented on worker/src/RTC/SvcConsumer.cpp
> +			// iterate all streams here anyway.
```suggestion
			// Let's iterate all spatial layers of the Producer (from highest to lowest) and
			// obtain their bitrate. Choose the highest one.
			// NOTE: When the Producer enables a higher spatial layer, initially the bitrate
			// oft could be less than the bitrate of a lower one. That's why we iterate all
			// spatial layers here anyway.
```

2023-03-30 09:50 UTC, ibc commented on worker/src/RTC/SvcConsumer.cpp
> +		if (this->encodingContext->IsKSvc())
```suggestion
		// When using K-SVC each spatial layer is independent of the others.
		if (this->encodingContext->IsKSvc())
```

2023-03-30 09:56 UTC, ibc approved these changes

2023-03-30 09:56 UTC, merged

2023-03-30 09:58 UTC, ibc commented
Releasing in 3.11.19 right now.