Add sender report trace event
versatica/mediasoup pull request #1267
Opened 2023-12-15 12:02 UTC by GithubUser8080

This PR adds a trace event for incoming RTCP sender reports from producers, to provide timestamp information in the node API. Covers use cases of server-side stream synchronization (like recording).

Usage 

`producer.enableTraceEvent(['sr'])`

emits

```
{
  type: 'sr',
  timestamp: 6348927,
  direction: 'in',
  info: {
    ssrc: 481847794,
    ntpSec: 3911629480,
    ntpFrac: 2788138149,
    rtpTs: 2712133695,
    packetCount: 928,
    octetCount: 75009
  }
}
```

2023-12-15 13:19 UTC, ibc requested changes
Looks good but Rust changes are also required.

2023-12-15 15:07 UTC, GithubUser8080 commented
Not familiar with rust so I am relying on the videoroom example for manual testing, hope it is enough.

2023-12-15 15:09 UTC, ibc commented
Just do `grep` looking for similar FBS types in worker/rust folder and will be easy.

2023-12-15 16:12 UTC, ibc commented
Run  `cargo fmt` to fix lint/clippy formating issues.

2023-12-15 16:24 UTC, jmillan reviewed
Looks good so far :+1:, just a cosmetic naming change requested.

2023-12-15 16:24 UTC, jmillan commented on worker/fbs/producer.fbs
> +    SRTraceInfo,
For consistency,

```suggestion
    SrTraceInfo,
```

2023-12-15 16:24 UTC, jmillan commented on worker/fbs/producer.fbs
> +table SRTraceInfo {
```suggestion
table SrTraceInfo {
```

2023-12-15 16:24 UTC, jmillan commented on worker/include/RTC/Producer.hpp
> +		void EmitTraceEventSRType(RTC::RTCP::SenderReport* report) const;
```suggestion
		void EmitTraceEventSrType(RTC::RTCP::SenderReport* report) const;
```

2023-12-15 16:24 UTC, jmillan commented on worker/src/RTC/Producer.cpp
> +			EmitTraceEventSRType(report);
```suggestion
			EmitTraceEventSrType(report);
```

2024-01-02 11:36 UTC, jmillan approved these changes

2024-01-02 13:41 UTC, ibc approved these changes

2024-01-02 19:55 UTC, ibc commented
Changelog entry missing and this must be documented in the website (I'll do).

2024-01-03 10:13 UTC, ibc requested changes

2024-01-03 10:13 UTC, ibc commented on rust/src/data_structures.rs
> +/// BWE info in trace event.
This is not "BWE info".

2024-01-03 12:01 UTC, ibc commented on rust/src/data_structures.rs
> +/// BWE info in trace event.
I'll merge and make this change in v3.

2024-01-03 12:02 UTC, merged

2024-01-08 07:41 UTC, GithubUser8080 commented
Thank you