liburing: print RLIMIT_MEMLOCK values upon ENOMEM
versatica/mediasoup pull request #1331
Opened 2024-02-13 10:37 UTC by jmillan

So the user can properly adjust the value.

2024-02-13 10:39 UTC, nazar-pc approved these changes

2024-02-13 10:40 UTC, ibc requested changes

2024-02-13 10:40 UTC, ibc commented on worker/src/DepLibUring.cpp
> +			if (getrlimit(RLIMIT_MEMLOCK, &l) == -1)
```suggestion
			if (getrlimit(RLIMIT_MEMLOCK, std::addressof(l)) == -1)
```

2024-02-13 10:40 UTC, ibc commented on worker/src/DepLibUring.cpp
> +				MS_WARN_TAG(info, "getrlimit() failed %s", std::strerror(errno));
```suggestion
				MS_WARN_TAG(info, "getrlimit() failed: %s", std::strerror(errno));
```

2024-02-19 08:25 UTC, ibc approved these changes

2024-02-19 14:00 UTC, merged