calculate sender rtt
versatica/mediasoup pull request #314
Opened 2019-06-14 12:15 UTC by yangjinecho

2019-06-14 12:20 UTC, jmillan commented
Looks quite nice! I'll comment on it very soon.

2019-06-14 12:27 UTC, ibc commented
Wow, this looks really amazing, @yangjinecho. Thanks a lot. We'll need some time to integrate it, but it will be done.

Super thanks!

Note for us: Include "Yang Jin @yangjinecho" in the CHANGELOG credits and in the next version announcement.

2019-06-14 13:15 UTC, jmillan commented
@yangjinecho,

The implemented extended report blocks are [1] and [2], right?
 
Could you indicate it by copying the header format ascii as done here [3]?

[1]: https://tools.ietf.org/html/rfc3611#section-4.4
[2]: https://tools.ietf.org/html/rfc3611#section-4.5
[3]: https://github.com/versatica/mediasoup/blob/v3/worker/include/RTC/RTCP/FeedbackPsRemb.hpp#L8

2019-06-14 13:50 UTC, yangjinecho commented
https://tools.ietf.org/html/rfc3611#section-4.4
https://tools.ietf.org/html/rfc3611#section-4.5

2019-06-14 20:31 UTC, jmillan requested changes

2019-06-14 20:31 UTC, jmillan commented on worker/include/RTC/RTCP/ReceiverExtendedReport.hpp
> +				uint16_t blockLength;
The above 3 fields are fixed for this type of block. They should be initialized here:

```c++
uint8_t blockType{ 4 };
uint8_t reserved{ 0 };
uint16_t blockLength{ 2 };
```

2019-06-14 20:31 UTC, jmillan commented on worker/include/RTC/RTCP/ReceiverExtendedReport.hpp
> +			void SetBlockLength(uint16_t blockLength);
The above 6 methods should simply not exist, since the field they are getting/setting is static and already set as per the previous comment.

2019-06-14 20:31 UTC, jmillan commented on worker/include/RTC/RTCP/SenderExtendedReport.hpp
> +				uint8_t reserved;
The above 2 fields are fixed for this type of block. They should be initialized here:

```c++
uint8_t blockType{ 5 };
uint8_t reserved{ 0 };
```

2019-06-14 20:31 UTC, jmillan commented on worker/include/RTC/RTCP/SenderExtendedReport.hpp
> +			void SetReserved(uint8_t reserved);
The above 4 methods should simply not exist, since the field they are getting/setting is static and already set as per the previous comment.

2019-06-14 20:31 UTC, jmillan commented on worker/include/RTC/RTCP/SenderExtendedReport.hpp
> +			void SetBlockLength(uint16_t blockLength);
The above 2 methods should not exist. The block length should be internally calculated considering the number of sub-blocks present.

2019-06-14 20:31 UTC, jmillan commented on worker/include/RTC/RTCP/ReceiverExtendedReport.hpp
> +			std::vector<ReceiverExtendedReport*> reports;
What's the reason for having a sub-block vector? The [Receiver Reference Time Report Block](https://tools.ietf.org/html/rfc3611#section-4.4) defines a single sub-block, hence there's no need to have a vector of sub-blocks but a single one.

2019-06-14 20:31 UTC, jmillan commented on worker/src/RTC/Producer.cpp
> +			report->SetBlockLength(2);
According to previous comments the 3 lines above should not exist.

2019-06-14 20:31 UTC, jmillan commented on worker/src/RTC/Producer.cpp
> +		if (true)
Superfluous condition.

2019-06-14 20:31 UTC, jmillan commented on worker/include/RTC/RTCP/CompoundPacket.hpp
> +			this->receiverExtendedReportPacket.AddReport(report);
This packet does not have the SSRC set has in the [spec](https://tools.ietf.org/html/rfc3611#section-2). Why is that?

2019-06-14 20:31 UTC, jmillan commented on worker/src/RTC/RtpStreamRecv.cpp
> +		MS_TRACE();
`MS_TRACE()` must always and only be present at the beginning of the method.

2019-06-14 20:31 UTC, jmillan commented on worker/src/RTC/Transport.cpp
> +				auto* ser = static_cast<RTC::RTCP::SenderExtendedReportPacket*>(packet);
You are assuming here that all incoming RTCP XR packets are composed merely by bocks of type 5. The packet could contain any kind of block instead, and this code will interpret all of them as if they where DLRR report blocks.

More on this later in the discussion section.

2019-06-14 20:31 UTC, jmillan commented on worker/src/RTC/RTCP/SenderExtendedReport.cpp
> +				MS_WARN_TAG(rtcp, "only support 5(DLRR Report Block), current is %hhu", header->blockType);
here `PRIu8` instead of `hhu`, as in the rest of the code.

2019-06-14 20:31 UTC, jmillan commented on worker/src/RTC/RTCP/ReceiverExtendedReport.cpp
> +				  "only support 4(Receiver Reference Time Report Block), current is %hhu",
here `PRIu8` instead of `hhu`, as in the rest of the code.

2019-06-14 20:31 UTC, jmillan commented on worker/src/RTC/RTCP/ReceiverExtendedReport.cpp
> +			MS_DUMP("  block length : %" PRIu16, GetBlockLength());
Above 3 lines should be removed.

2019-06-14 20:31 UTC, jmillan commented on worker/include/RTC/RTCP/SenderExtendedReport.hpp
> +			};
This header does not represent a DLRR Report Block as per the [spec](https://tools.ietf.org/html/rfc3611#section-4.5)

The bock is defined by:

- blockType = 5
- reserved = 0
- blockLength = (depends on number of sub-blocks)
- N * sub-blocks.

The sub-block is defined by:
- ssrc
- lrr
- dlrr

2019-06-14 20:42 UTC, jmillan commented
@yangjinecho,

[RFC 3611](https://tools.ietf.org/html/rfc3611) defines a single RTCP packet. Here you have defined two, one for each of the **blocks** you have implemented.

There should be a single RTCP XR packet implementation which should be composed by blocks, two of which you have already implemented.

I'll come back soon with a change proposal which will include some naming changes in order to reflect the spec.

Apart from that, I believe the RTT is well calculated and the flow of the methods is well done, well done! :-)

I've made few comments on the PR, which you could address at your convenience.

Thanks a lot!

2019-06-15 16:08 UTC, jmillan commented
Hi @yangjinecho,

Thanks a lot for the modifications.

As I told yesterday, I've made a proposal for the new RTCP RX packet and the different blocks . You can see it [here](https://gist.github.com/jmillan/aba691999380469906fc727a10d32beb). Beware that it is pseudo-code.

This is what it represents:

- There is a new RTCP XR packet. (Only one new RTCP packet as the spec defines)
- All 7 block types are defined.
- The new packet contains a vector of blocks.
- The clases of the 2 blocks you have implemented are defined (RRT and DLRR) too.
- The class representing the DLRR's sub-block is also defined. 

This `single` new packet and blocks (plus DLRR sub-block) definition represent IMHO clearly the specification plus comes one with the existing RTCP implementation in mediasoup.

Would you consider such a modification? 

Thanks a bunch.

2019-06-16 04:39 UTC, jmillan commented
I've just renamed `DelaySinceLastRr::SubBlock` by `DelaySinceLastRr::SsrcInfo` in the [gist](https://gist.github.com/jmillan/aba691999380469906fc727a10d32beb)

2019-06-17 16:41 UTC, jmillan commented
@yangjinecho,

I could help with the implementation of my proposal. We're already grateful you came with that nice piece of code.

You'll have to grant me access though :-)

2019-06-17 22:23 UTC, ibc commented
Also take into account Codacy report: https://app.codacy.com/app/versatica/mediasoup/pullRequest?prid=3721268#newIssuesView

2019-06-24 14:43 UTC, jmillan commented
Thanks @yangjinecho, I've already got access to your branch

2019-06-25 18:06 UTC, jmillan commented
Hi,

I've [refactored](https://github.com/yangjinecho/mediasoup/commit/6fe680cece5da57cba417844b537863402c16093?diff=unified) the RTCP XR code according to what I suggested. 

@yangjinecho, I have made a `git push --force` in the branch! That's because I've merged current mediasoup v3 on it.

Tomorrow I'll have a last check in case I've missed any cosmetics anywhere.

Feel free to review it!

2019-06-26 06:05 UTC, ibc requested changes

2019-06-26 06:05 UTC, ibc commented on worker/include/RTC/RTCP/XR.hpp
> +
Can we remove this empty line?

2019-06-26 06:05 UTC, ibc commented on worker/include/RTC/RTCP/XR.hpp
> +			;
Ugly ";" line. Remove.

2019-06-26 06:05 UTC, ibc commented on worker/include/RTC/RTCP/XR.hpp
> +			for (auto* report : this->reports)
Please always add { } in loops.

2019-06-26 06:05 UTC, ibc commented on worker/include/RTC/RTCP/XrDelaySinceLastRr.hpp
> +
Remove empty line.

2019-06-26 06:05 UTC, ibc commented on worker/include/RTC/RTCP/XrDelaySinceLastRr.hpp
> +				uint8_t raw[sizeof(Body)]{ 0 };
Is such a `{ 0 }` initialization needed?

2019-06-26 06:05 UTC, ibc commented on worker/include/RTC/RTCP/XrDelaySinceLastRr.hpp
> +		public:
Move `static` functions and members to the top of the class declaration.

2019-06-26 06:05 UTC, ibc commented on worker/include/RTC/RTCP/XR.hpp
> +			ExtendedReportBlock::Type GetType() const;
Move this line below with the rest of public methods.

2019-06-26 06:05 UTC, ibc commented on worker/include/RTC/RTCP/XrDelaySinceLastRr.hpp
> +			Iterator Begin();
Move those methods below with the rest of public own methods.

2019-06-26 06:05 UTC, ibc commented on worker/include/RTC/RTCP/XrReceiverReferenceTime.hpp
> +
Remove empty line.

2019-06-26 06:05 UTC, ibc commented on worker/include/RTC/RTCP/XrReceiverReferenceTime.hpp
> +			// Locally generated Report. Holds the data internally.
Add `public:` after class constructor/destructor for the rest of public methods.

2019-06-26 06:05 UTC, ibc commented on worker/include/RTC/RTCP/XR.hpp
> +		// Inline ExtendedReportBlock methods.
Replace with:

```c++
/* Inline ExtendedReportBlock methods. */
```

2019-06-26 06:05 UTC, ibc commented on worker/src/RTC/RTCP/XrDelaySinceLastRr.cpp
> +
Remove empty line.

2019-06-26 06:05 UTC, ibc commented on worker/src/RTC/RTCP/XrDelaySinceLastRr.cpp
> +
Remove empty line.

2019-06-26 06:05 UTC, ibc commented on worker/src/RTC/RTCP/XrDelaySinceLastRr.cpp
> +
Remove empty line.

2019-06-26 06:05 UTC, ibc commented on worker/src/RTC/RTCP/XrDelaySinceLastRr.cpp
> +
Remove empty line.

2019-06-26 06:05 UTC, ibc commented on worker/src/RTC/RTCP/XrReceiverReferenceTime.cpp
> +
Remove empty line.

2019-06-26 06:05 UTC, ibc commented on worker/src/RTC/RTCP/XrReceiverReferenceTime.cpp
> +
Remove empty line.

2019-06-26 06:05 UTC, ibc commented on worker/src/RTC/Transport.cpp
> +						default:
Add `{ }` for `default:` body since `case` above uses brackets.

2019-06-26 06:05 UTC, ibc commented on worker/test/src/RTC/RTCP/TestXr.cpp
> +
Remove empty line.

2019-06-26 06:05 UTC, ibc commented on worker/test/src/RTC/RTCP/TestXr.cpp
> +		/* Total size:
Do we really need this kind of `/* */` comments here? Can't we just use `//` lines as usual?

2019-06-26 06:05 UTC, ibc commented on worker/test/src/RTC/RTCP/TestXr.cpp
> +		/* Total size:
Idem.

2019-06-26 06:07 UTC, ibc commented
Does the calculated RTT make sense in the stats? A cool way to test it is by using OSX NetworkConditioner by setting uplink or downlink delay of 1-2 seconds. So the RTT should be higher than that value.

2019-06-26 07:46 UTC, jmillan commented on worker/include/RTC/RTCP/XrDelaySinceLastRr.hpp
> +		inline DelaySinceLastRr::SsrcInfo::SsrcInfo()
hahah

2019-06-26 07:51 UTC, ibc commented
CODACY NOT HAPPY

2019-06-26 08:14 UTC, ibc commented
Some missing stuff in this PR:

* fuzzer stuf for new RTCP packets.

* [Travis fails](https://travis-ci.com/versatica/mediasoup/jobs/211054770):

```
REQUIRE(std::memcmp(bufferPacket1, bufferPacket2, packet1->GetSize()) == 0);
```

Probably missing:

```c++
#include <cstring>  // std::memcpy()
```

* In addition: Must add the new stat field (I assume it is in the Producer RtpStreamRecv stats) in the [doc](https://mediasoup.org/documentation/v3/mediasoup/rtc-statistics/).

2019-06-26 08:38 UTC, jmillan commented
- [ x ] Verify RTT values are reliable.
- [ ] Fuzzer stuf for new RTCP packets.
- [ x ] Fix Travis failure.
- [ x ] Add the new stat field  in the doc.

2019-06-26 09:37 UTC, jmillan approved these changes

2019-07-16 08:10 UTC, jmillan commented
Branch has been merged to v3.

Thanks a lot @yangjinecho!

2019-07-16 08:10 UTC, closed without merging