Fix PayloadChannel cause terminate
versatica/mediasoup pull request #569
Opened 2021-05-29 00:54 UTC by aggresss

2021-05-31 13:05 UTC, ibc requested changes
Thanks, good catch. Just a cosmetic change requested.

2021-05-31 13:05 UTC, ibc commented on worker/include/PayloadChannel/PayloadChannelSocket.hpp
> +		uint8_t* readBuffer;
Let's follow code convention:

```suggestion
		// Allocated by this.
		uint8_t* readBuffer{ nullptr };
		// Others.
		size_t msgStart{ 0u }; // Where the latest message starts.
```

2021-05-31 13:10 UTC, ibc commented on worker/include/PayloadChannel/PayloadChannelSocket.hpp
> +		uint8_t* readBuffer;
I'm gonna apply this and merge.

2021-05-31 13:10 UTC, ibc approved these changes

2021-05-31 13:16 UTC, merged

2021-05-31 13:18 UTC, ibc commented
Released in mediasoup 3.7.9

2021-06-01 08:28 UTC, jmillan reviewed
:+1: