Rust updates and optimizations around communication performance
versatica/mediasoup pull request #666
Opened 2021-10-08 17:10 UTC by nazar-pc

Changelog update has all major changes mentioned.

The big topic here is transition from file descriptors usage to native FFI function calls between C++ and Rust for lower latency, lower memory usage and better cross-platform support (Windows support is coming!).

The way it is implemented is the following:
* each channel construction has 2 pairs of optional parameters:
  * `channelReadFn` and `channelReadCtx` represent a function call (this is C ABI, so we can't send closures, we need static function and its context)
    * it is called by C++ when worker wants to read a message
    * with every call C++ sends over `uv_async_t` handle, so Rust (or any other language, really) can ping worker's `libuv` to try to read next message
      * because of this C++ does one initial call proactively to hand over this handle to the other side
  * `ChannelWriteCtx` and `ChannelWriteFn` also represent a similar function
    * it is called by C++ when worker wants to write a message
    * because Rust side here is thread-safe, this is immediately delivered to Rust and does all of the business logic before returning, so no need for additional notifications
* the implementation allows C++ worker to share memory with Rust using raw pointer without even copying it
* Rust though has to allocate for outgoing messages because it doesn't know when worker will be ready to read

I do not like how many arguments there is in worker instantiation now, but at the same time I don't see a huge potential for improvements either as we are limited by shared C ABI here. Open to suggestions.

2021-10-09 12:06 UTC, ibc reviewed
This is awesome. Definitely I need some time before I can properly review this (Jose is gonna be out for a while for very good reasons). So just a question/concern for now:

Here comm between Rust and worker is sync meaning that if Rust layer (i.e. the Rust app) blocks or makes the CPU be super busy, that would also block and affect the worker loop. Hopefully I'm wrong given that uv_async is used in worker.

2021-10-09 12:06 UTC, ibc commented on worker/src/Channel/ChannelSocket.cpp
> +			// Read while there are new messages
Dot at the end of comments 😀

2021-10-09 12:06 UTC, ibc commented on worker/src/PayloadChannel/PayloadChannelSocket.cpp
> +			// Read while there are new messages
Same

2021-10-09 12:06 UTC, ibc commented on worker/src/Channel/ChannelSocket.cpp
> +		if (this->producerSocket)
Line break please

2021-10-09 12:14 UTC, nazar-pc commented
> Here comm between Rust and worker is sync meaning that if Rust layer (i.e. the Rust app) blocks or makes the CPU be super busy, that would also block and affect the worker loop. Hopefully I'm wrong given that uv_async is used in worker.

You are correct here. When worker sends a response or notification into Rust this is definitely something everyone should keep in mind, it will steal some time from worker, but presumably very little. On the flip side the whole things is significantly more efficient, so developer now can decide whether to do memory copy and send it to another thread or process in place.

Communication from Rust to worker is async, so there is no such problem there.

2021-10-10 17:19 UTC, ibc commented on src/Channel.ts
> +			setImmediate(() => this.emit(String(msg.targetId), msg.event, msg.data));
Why this? it should be a string already. And BTW I'm afraid there are gonna be conflicts here now since these files are now in `node/src/` instead.

2021-10-10 18:03 UTC, nazar-pc commented on src/Channel.ts
> +			setImmediate(() => this.emit(String(msg.targetId), msg.event, msg.data));
The reason is that **technically** `targetId` can be both a string (UUID) and a number (process ID), while function signature is:
```typescript
NodeJS.EventEmitter.emit(event: string | symbol, ...args: any[]): boolean
```

So using `String()` is semantically correct to use to make sure we always end up with a string there. I know it worked before, but it felt wrong.

> there are gonna be conflicts here

It is fine, I will resolve conflicts after your changes are merged.

2021-10-10 18:21 UTC, ibc commented on src/Channel.ts
> +			setImmediate(() => this.emit(String(msg.targetId), msg.event, msg.data));
My changes are already merged :)

2021-10-10 18:25 UTC, nazar-pc commented on src/Channel.ts
> +			setImmediate(() => this.emit(String(msg.targetId), msg.event, msg.data));
#673 still isn't :thinking:

2021-10-10 18:38 UTC, ibc commented on src/Channel.ts
> +			setImmediate(() => this.emit(String(msg.targetId), msg.event, msg.data));
My fault, I was pretty sure I clicked Merge button but I didn't... done now

2021-10-11 04:41 UTC, nazar-pc commented
Merge conflicts resolved

2021-11-08 14:15 UTC, jmillan approved these changes
👏 Great

2021-11-20 16:00 UTC, nazar-pc commented
Merged latest updates from `v3` here.
@ibc do you have any thoughts on this yet?

2021-11-20 16:09 UTC, ibc commented
I'll review tomorrow

2021-11-25 09:50 UTC, ibc commented on worker/include/Channel/ChannelNotifier.hpp
> +		static void Emit(uint64_t targetId, const char* event);
In which case do we emit with a number instead of a string?

2021-11-25 09:52 UTC, ibc requested changes

2021-11-25 09:52 UTC, ibc commented on worker/include/common.hpp
> +// Returns `ChannelReadFree` on successful read that must be used to free `message`
Please dot after all comments here.

2021-11-25 09:54 UTC, ibc commented on worker/src/Channel/ChannelSocket.cpp
>  	/* Static. */
```suggestion
	/* Static methods for UV callbacks. */
```

2021-11-25 09:57 UTC, ibc commented on worker/src/Worker.cpp
> +	Channel::ChannelNotifier::Emit(Logger::pid, "running");
I see here.

2021-11-25 09:57 UTC, ibc reviewed
Just a cosmetic change. Code looks great.

2021-11-26 08:02 UTC, ibc approved these changes
PR 666 approved (once CI doesn't complain)

2021-11-26 14:23 UTC, ibc commented
@nazar-pc feel free to merge :)

2021-11-26 14:35 UTC, merged