Added support for RTP abs-capture-time header
versatica/mediasoup pull request #761
Opened 2022-01-26 08:46 UTC by oto313

2022-01-26 12:26 UTC, ibc approved these changes
Thanks.

2022-01-26 12:27 UTC, ibc commented
Running CI checks before merging.

2022-01-26 12:30 UTC, ibc requested changes
clang linter complains: https://github.com/versatica/mediasoup/runs/4951301699?check_suite_focus=true

Please run `make format` in `worker/` folder, and ensure everything is ok running `npm run lint` and `npm test` and push.

2022-01-26 14:26 UTC, oto313 commented
Should be ok now.

2022-01-26 14:28 UTC, nazar-pc commented
Can you also make similar changes to Rust side, please?

2022-01-26 18:47 UTC, oto313 commented
I tried to add support also for rust, but I never programmed in rust. In producer.rs I did not find any equivalent of MangleRtpPacket (like in Producer.cpp). So I dont know if the changes are sufficient. Also I did not tested it

2022-01-26 18:48 UTC, ibc approved these changes
Do you approve @nazar-pc?

2022-01-26 18:49 UTC, ibc commented
> I tried to add support also for rust, but I never programmed in rust. In producer.rs I did not find any equivalent of MangleRtpPacket (like in Producer.cpp). So I dont know if the changes are sufficient. Also I did not tested it

The Rust part is equivalent to the Node part. C++ code is just for the worker.

2022-01-26 18:51 UTC, nazar-pc approved these changes
Looks fine to me

2022-01-26 18:55 UTC, nazar-pc commented
Looks like tests need to be updated accordingly

2022-01-26 20:17 UTC, ibc requested changes
Yup, tests failing. This is in both Node tests and Rust tests.

2022-01-26 21:19 UTC, oto313 commented
Ok I fixed tests both node and rust (good to know that you must  run "npm run typescript:build" before running tests - my test was successful but with old code)

2022-01-26 22:08 UTC, oto313 commented
Ok last error in rust: Failed to create Pipe transport: Response { reason: "uv_udp_bind() failed [transport:udp, ip:'127.0.0.1', port:60000]: permission denied. I dont know how to fix that.

2022-01-26 22:10 UTC, nazar-pc commented
I just restarted it. Port is hardcoded, maybe it happened to be used on that particular run (never happened before, but probable).

2022-01-27 12:01 UTC, ibc commented
Merging this. Thanks a lot.

2022-01-27 12:01 UTC, ibc approved these changes

2022-01-27 12:01 UTC, merged

2022-01-27 12:06 UTC, ibc commented
Released in mediasoup 3.9.6.