Fix VP9 kSVC forwarding logic to not forward lower unneded layers
versatica/mediasoup pull request #778
Opened 2022-02-28 09:17 UTC by ggarber

Description:

When using VP9 in kSVC model (current supported mode in WebRTC) the higher spatial layers are independent of the lower spatial layers and need to be filtered.  Otherwise we are consuming much more bandwidth tan needed (30%?).  

![image](https://user-images.githubusercontent.com/512252/155956656-20623870-36e5-4d3d-a4af-34e9bf20f0f7.png)
https://www.w3.org/TR/webrtc-svc/

To detect if it is a keyframe packet that needs to be forwarded even if it is a lower spatial layer this change checks the P bit in the VP9 header that distinguishes frames that are encoded independently of other frames (key frames).

Test Plan:
Ran producer and consumer locally and changed MaxOutgoingBitrate of the consumer to allocate different bitrates and check the video can always be decoded by the consumer.

2022-02-28 10:53 UTC, ibc requested changes

2022-02-28 10:53 UTC, ibc commented on worker/src/RTC/Codecs/VP9.cpp
> +				  (context->IsKSvc() && this->payloadDescriptor->p && packetSpatialLayer != tmpSpatialLayer))
Please merge both conditions into one. No reason for having a if inside another if.

2022-02-28 13:52 UTC, ibc approved these changes

2022-02-28 13:53 UTC, ibc commented
Will merge later today

2022-03-01 09:52 UTC, jmillan approved these changes

2022-03-01 11:41 UTC, merged

2022-03-01 11:57 UTC, ibc commented
Release in 3.9.8