[PoC] Add generic types for appData
versatica/mediasoup pull request #869
Opened 2022-07-15 16:10 UTC by mango-martin

Regarding #832 

I've been pretty swamped lately but I finally got around to do a barebones prototype of the suggested changes. I'll have to preface that I am not very fluid in TypeScript. But from what VSCode tells me it's been successful. I'll attach some screenshots to show the impact of the changes.

![typedecl](https://user-images.githubusercontent.com/82488647/179261753-33034d70-e857-439d-aa4f-a2945fe67b5e.PNG)
![correctinf](https://user-images.githubusercontent.com/82488647/179261738-197261fd-c696-4172-b177-8edf95912f4f.PNG)
![random](https://user-images.githubusercontent.com/82488647/179262942-52ca66d0-06c2-4e4c-b71e-f463f840f4c2.PNG)

And for a reason I honestly don't really understand, this even works with type inference of the provided appData even without providing a generic type
![router](https://user-images.githubusercontent.com/82488647/179262331-720d062d-59db-47a6-91b4-bd44a9541a14.PNG)

Cheers

2022-07-15 16:14 UTC, mango-martin commented on node/src/Router.ts
> +export type AppData = {
I put this here temporarily because I didn't really know where else to keep it

2022-07-17 17:49 UTC, mango-martin commented
I've updated the PR already to cover all of the code - it was much more straightforward than I thought.
Few questions remain about naming the types individually (in some classes a general name would conflict with another type that was declared at the class level - so I went with naming them individually). This might be a bit hard to maintain.
Another thing is the location of my helper type `AppData`. Basically you could replace every occurence of AppData with Record<string, unknown> but it just seemed reasonable to have a bit of a shorter name for that.
Lastly about formatting. Because The added types would often exceed the linter limit of characters per line, I had to put in a line-break.

Let me know how you want to proceed with this. Or not, up to you :D

2022-09-19 15:25 UTC, ibc commented
We don't forget about this. It's just that we have been very busy.

2022-11-05 21:04 UTC, ibc requested changes

2022-11-05 21:04 UTC, ibc commented on node/src/index.ts
> +}
Please let's not do this here. Add this into `types.ts` instead.

2023-03-31 11:05 UTC, ibc commented
@mango-martin I've replaced your PR with this one https://github.com/versatica/mediasoup/pull/1046 due to missing additions that shown up after we migrated tests to TypeScript. Credits to you. Thanks!

2023-03-31 11:05 UTC, closed without merging