Added option to automatically determine port to WebRtcServer
versatica/mediasoup pull request #908
Opened 2022-09-12 01:08 UTC by satoren

If port is not specified at createWebRtcServer, automatically determine the port of the webrtcserver by Worker's port range

2022-09-12 01:29 UTC, nazar-pc commented
Same thing I commented on original PR :slightly_smiling_face:  https://github.com/versatica/mediasoup/pull/834#issuecomment-1166606629

2022-09-12 09:42 UTC, ibc reviewed
Just cosmetic changes required.

2022-09-12 09:42 UTC, ibc commented on worker/src/RTC/WebRtcServer.cpp
> +					if (listenInfo.port != 0)
Please blank line before the if condition.

2022-09-12 09:42 UTC, ibc commented on worker/src/RTC/WebRtcServer.cpp
>  			if (jsonPortIt == jsonListenInfo.end())
These conditions are a bit hard to read. We usually handle first the case in which value is properly given, then lack of given value (so ser port to 0), then the throw due to invalid value.

2022-09-20 12:37 UTC, ibc requested changes

2022-09-20 12:37 UTC, ibc commented on worker/src/RTC/WebRtcServer.cpp
> +			listenInfo.port = port;
Please blank line after }

2022-09-20 12:37 UTC, ibc commented on worker/src/RTC/WebRtcServer.cpp
> +					RTC::TcpServer* tcpServer;
Blank line after this line as above, please

2022-09-21 11:39 UTC, ibc commented
Lint or something is failing in CI

2022-09-28 14:29 UTC, jmillan approved these changes

2022-09-28 16:02 UTC, ibc commented
I won't merge it yet since I want to write doc in mediasoup-website project before merging it. If you wish to make a PR to the docs project, you are welcome. Otherwise I'll do hopefully this week.

2022-10-03 16:34 UTC, ibc approved these changes

2022-10-03 16:37 UTC, merged

2022-10-03 16:43 UTC, ibc commented
Released in 3.10.8